import { Duration } from 'angular-odata';

//#region ODataApi Imports
import { Etiqueta } from '../Metadatos/etiqueta.entity';
import { Recurso } from '../Recursos/recurso.entity';
import { Documento } from '../Documentos/documento.entity';
import { Archivo } from '../Documentos/archivo.entity';
import { Oficina } from '../Lugares/oficina.entity';
import { Empleado } from '../Personas/empleado.entity';
import { RequirenteEnEspera } from '../Personas/requirenteenespera.entity';
import { RequirenteCaso } from './requirentecaso.entity';
import { EmpleadoCaso } from './empleadocaso.entity';
import { Intervencion } from './intervencion.entity';
import { CasoJudiciable } from './casojudiciable.entity';
import { CategoriaCaso } from './categoriacaso.entity';
import { Audiencia } from './audiencia.entity';
import { Avenimiento } from './avenimiento.entity';
import { NotaAvenimiento } from './notaavenimiento.entity';
import { SubMateria } from './submateria.entity';
import { HistoricoSubmateria } from './historicosubmateria.entity';
import { CategoriaCasoCaso } from './categoriacasocaso.entity';
import { HistoricoResponsable } from './historicoresponsable.entity';
import { Cita } from '../Agenda/cita.entity';
import { EtiquetaModel } from '../Metadatos/etiqueta.model';
import { RecursoModel } from '../Recursos/recurso.model';
import { DocumentoModel } from '../Documentos/documento.model';
import { ArchivoModel } from '../Documentos/archivo.model';
import { OficinaModel } from '../Lugares/oficina.model';
import { EmpleadoModel } from '../Personas/empleado.model';
import { RequirenteEnEsperaModel } from '../Personas/requirenteenespera.model';
import { CasoModel } from './caso.model';
import { RequirenteCasoModel } from './requirentecaso.model';
import { EmpleadoCasoModel } from './empleadocaso.model';
import { IntervencionModel } from './intervencion.model';
import { CasoJudiciableModel } from './casojudiciable.model';
import { CategoriaCasoModel } from './categoriacaso.model';
import { AudienciaModel } from './audiencia.model';
import { AvenimientoModel } from './avenimiento.model';
import { NotaAvenimientoModel } from './notaavenimiento.model';
import { SubMateriaModel } from './submateria.model';
import { HistoricoSubmateriaModel } from './historicosubmateria.model';
import { CategoriaCasoCasoModel } from './categoriacasocaso.model';
import { HistoricoResponsableModel } from './historicoresponsable.model';
import { CitaModel } from '../Agenda/cita.model';
import { EtiquetaCollection } from '../Metadatos/etiqueta.collection';
import { RecursoCollection } from '../Recursos/recurso.collection';
import { DocumentoCollection } from '../Documentos/documento.collection';
import { ArchivoCollection } from '../Documentos/archivo.collection';
import { OficinaCollection } from '../Lugares/oficina.collection';
import { EmpleadoCollection } from '../Personas/empleado.collection';
import { RequirenteEnEsperaCollection } from '../Personas/requirenteenespera.collection';
import { CasoCollection } from './caso.collection';
import { RequirenteCasoCollection } from './requirentecaso.collection';
import { EmpleadoCasoCollection } from './empleadocaso.collection';
import { IntervencionCollection } from './intervencion.collection';
import { CasoJudiciableCollection } from './casojudiciable.collection';
import { CategoriaCasoCollection } from './categoriacaso.collection';
import { AudienciaCollection } from './audiencia.collection';
import { AvenimientoCollection } from './avenimiento.collection';
import { NotaAvenimientoCollection } from './notaavenimiento.collection';
import { SubMateriaCollection } from './submateria.collection';
import { HistoricoSubmateriaCollection } from './historicosubmateria.collection';
import { CategoriaCasoCasoCollection } from './categoriacasocaso.collection';
import { HistoricoResponsableCollection } from './historicoresponsable.collection';
import { CitaCollection } from '../Agenda/cita.collection';
//#endregion

export interface Caso {
  //#region ODataApi Properties
  subMateriaId?: number;
  oficinaId?: number;
  desde: Date;
  modificacion?: Date;
  hasta?: Date;
  observaciones?: string;
  responsableId?: number;
  fechaResponsable?: Date;
  referenteId?: number;
  estado?: number;
  etapaAvenimiento: boolean;
  archivado: boolean;
  reclamoAdministrativo?: boolean;
  enEspera: boolean;
  enAtencion: boolean;
  esNuevo: boolean;
  esEliminable: boolean;
  id: number;
  rev?: ArrayBuffer;
  key?: string;
  type?: string;
  shortname?: string;
  name?: string;
  longname?: string;
  oficina?: Oficina;
  subMateria?: SubMateria;
  historicoSubmaterias?: HistoricoSubmateria[];
  etiquetas?: Etiqueta[];
  intervenciones?: Intervencion[];
  audiencias?: Audiencia[];
  avenimientos?: Avenimiento[];
  notaAvenimientos?: NotaAvenimiento[];
  categorias?: CategoriaCasoCaso[];
  citas?: Cita[];
  originantes?: Caso[];
  originados?: Caso[];
  expedientes?: CasoJudiciable[];
  requirentes?: RequirenteCaso[];
  requirentesEnEspera?: RequirenteEnEspera[];
  referente?: Empleado;
  responsable?: Empleado;
  subResponsables?: EmpleadoCaso[];
  historicoResponsables?: HistoricoResponsable[];
  categoria?: CategoriaCaso;
  esperasSinAtender?: RequirenteEnEspera[];
  recursos?: Recurso[];
  documentos?: Documento[];
  archivo?: Archivo[];
  //#endregion
}