import { Duration } from 'angular-odata';

//#region ODataApi Imports
import { OutlookItem } from './outlookitem.entity';
import { FreeBusyStatus } from './freebusystatus.enum';
import { EventType } from './eventtype.enum';
import { Importance } from './importance.enum';
import { OnlineMeetingProviderType } from './onlinemeetingprovidertype.enum';
import { Sensitivity } from './sensitivity.enum';
import { Recipient } from './recipient.entity';
import { DateTimeTimeZone } from './datetimetimezone.entity';
import { Location } from './location.entity';
import { Attendee } from './attendee.entity';
import { ResponseStatus } from './responsestatus.entity';
import { ItemBody } from './itembody.entity';
import { OnlineMeetingInfo } from './onlinemeetinginfo.entity';
import { PatternedRecurrence } from './patternedrecurrence.entity';
import { Calendar } from './calendar.entity';
import { Extension } from './extension.entity';
import { Attachment } from './attachment.entity';
import { MultiValueLegacyExtendedProperty } from './multivaluelegacyextendedproperty.entity';
import { SingleValueLegacyExtendedProperty } from './singlevaluelegacyextendedproperty.entity';
import { RecipientModel } from './recipient.model';
import { DateTimeTimeZoneModel } from './datetimetimezone.model';
import { LocationModel } from './location.model';
import { AttendeeModel } from './attendee.model';
import { ResponseStatusModel } from './responsestatus.model';
import { ItemBodyModel } from './itembody.model';
import { OnlineMeetingInfoModel } from './onlinemeetinginfo.model';
import { PatternedRecurrenceModel } from './patternedrecurrence.model';
import { CalendarModel } from './calendar.model';
import { OutlookItemModel } from './outlookitem.model';
import { EventModel } from './event.model';
import { ExtensionModel } from './extension.model';
import { AttachmentModel } from './attachment.model';
import { MultiValueLegacyExtendedPropertyModel } from './multivaluelegacyextendedproperty.model';
import { SingleValueLegacyExtendedPropertyModel } from './singlevaluelegacyextendedproperty.model';
import { RecipientCollection } from './recipient.collection';
import { DateTimeTimeZoneCollection } from './datetimetimezone.collection';
import { LocationCollection } from './location.collection';
import { AttendeeCollection } from './attendee.collection';
import { ResponseStatusCollection } from './responsestatus.collection';
import { ItemBodyCollection } from './itembody.collection';
import { OnlineMeetingInfoCollection } from './onlinemeetinginfo.collection';
import { PatternedRecurrenceCollection } from './patternedrecurrence.collection';
import { CalendarCollection } from './calendar.collection';
import { OutlookItemCollection } from './outlookitem.collection';
import { EventCollection } from './event.collection';
import { ExtensionCollection } from './extension.collection';
import { AttachmentCollection } from './attachment.collection';
import { MultiValueLegacyExtendedPropertyCollection } from './multivaluelegacyextendedproperty.collection';
import { SingleValueLegacyExtendedPropertyCollection } from './singlevaluelegacyextendedproperty.collection';
//#endregion

export interface Event extends OutlookItem {
  //#region ODataApi Properties
  allowNewTimeProposals?: boolean;
  attendees?: Attendee[];
  body?: ItemBody;
  bodyPreview?: string;
  end?: DateTimeTimeZone;
  hasAttachments?: boolean;
  iCalUId?: string;
  importance?: Importance;
  isAllDay?: boolean;
  isCancelled?: boolean;
  isOnlineMeeting?: boolean;
  isOrganizer?: boolean;
  isReminderOn?: boolean;
  location?: Location;
  locations?: Location[];
  onlineMeeting?: OnlineMeetingInfo;
  onlineMeetingProvider?: OnlineMeetingProviderType;
  onlineMeetingUrl?: string;
  organizer?: Recipient;
  originalEndTimeZone?: string;
  originalStart?: Date;
  originalStartTimeZone?: string;
  recurrence?: PatternedRecurrence;
  reminderMinutesBeforeStart?: number;
  responseRequested?: boolean;
  responseStatus?: ResponseStatus;
  sensitivity?: Sensitivity;
  seriesMasterId?: string;
  showAs?: FreeBusyStatus;
  start?: DateTimeTimeZone;
  subject?: string;
  transactionId?: string;
  type?: EventType;
  webLink?: string;
  attachments?: Attachment[];
  calendar?: Calendar;
  extensions?: Extension[];
  instances?: Event[];
  multiValueExtendedProperties?: MultiValueLegacyExtendedProperty[];
  singleValueExtendedProperties?: SingleValueLegacyExtendedProperty[];
  //#endregion
}