import { Duration } from 'angular-odata';

//#region ODataApi Imports
import { DirectoryObject } from './directoryobject.entity';
import { AssignedLicense } from './assignedlicense.complex';
import { OnPremisesProvisioningError } from './onpremisesprovisioningerror.complex';
import { AssignedLabel } from './assignedlabel.complex';
import { LicenseProcessingState } from './licenseprocessingstate.complex';
import { AppRoleAssignment } from './approleassignment.entity';
import { Calendar } from './calendar.entity';
import { Event } from './event.entity';
import { ProfilePhoto } from './profilephoto.entity';
import { Drive } from './drive.entity';
import { Site } from './site.entity';
import { Extension } from './extension.entity';
import { Onenote } from './onenote.entity';
import { Team } from './team.entity';
import { ResourceSpecificPermissionGrant } from './resourcespecificpermissiongrant.entity';
import { GroupSetting } from './groupsetting.entity';
import { Conversation } from './conversation.entity';
import { ConversationThread } from './conversationthread.entity';
import { GroupLifecyclePolicy } from './grouplifecyclepolicy.entity';
import { PlannerGroup } from './plannergroup.entity';
import { AssignedLicenseModel } from './assignedlicense.model';
import { OnPremisesProvisioningErrorModel } from './onpremisesprovisioningerror.model';
import { AssignedLabelModel } from './assignedlabel.model';
import { LicenseProcessingStateModel } from './licenseprocessingstate.model';
import { DirectoryObjectModel } from './directoryobject.model';
import { AppRoleAssignmentModel } from './approleassignment.model';
import { CalendarModel } from './calendar.model';
import { EventModel } from './event.model';
import { ProfilePhotoModel } from './profilephoto.model';
import { DriveModel } from './drive.model';
import { SiteModel } from './site.model';
import { ExtensionModel } from './extension.model';
import { OnenoteModel } from './onenote.model';
import { TeamModel } from './team.model';
import { ResourceSpecificPermissionGrantModel } from './resourcespecificpermissiongrant.model';
import { GroupSettingModel } from './groupsetting.model';
import { ConversationModel } from './conversation.model';
import { ConversationThreadModel } from './conversationthread.model';
import { GroupLifecyclePolicyModel } from './grouplifecyclepolicy.model';
import { PlannerGroupModel } from './plannergroup.model';
import { AssignedLicenseCollection } from './assignedlicense.collection';
import { OnPremisesProvisioningErrorCollection } from './onpremisesprovisioningerror.collection';
import { AssignedLabelCollection } from './assignedlabel.collection';
import { LicenseProcessingStateCollection } from './licenseprocessingstate.collection';
import { DirectoryObjectCollection } from './directoryobject.collection';
import { AppRoleAssignmentCollection } from './approleassignment.collection';
import { CalendarCollection } from './calendar.collection';
import { EventCollection } from './event.collection';
import { ProfilePhotoCollection } from './profilephoto.collection';
import { DriveCollection } from './drive.collection';
import { SiteCollection } from './site.collection';
import { ExtensionCollection } from './extension.collection';
import { OnenoteCollection } from './onenote.collection';
import { TeamCollection } from './team.collection';
import { ResourceSpecificPermissionGrantCollection } from './resourcespecificpermissiongrant.collection';
import { GroupSettingCollection } from './groupsetting.collection';
import { ConversationCollection } from './conversation.collection';
import { ConversationThreadCollection } from './conversationthread.collection';
import { GroupLifecyclePolicyCollection } from './grouplifecyclepolicy.collection';
import { PlannerGroupCollection } from './plannergroup.collection';
//#endregion

export interface Group extends DirectoryObject {
  //#region ODataApi Properties
  assignedLabels?: AssignedLabel[];
  assignedLicenses?: AssignedLicense[];
  classification?: string;
  createdDateTime?: Date;
  description?: string;
  displayName?: string;
  expirationDateTime?: Date;
  groupTypes: string[];
  hasMembersWithLicenseErrors?: boolean;
  licenseProcessingState?: LicenseProcessingState;
  mail?: string;
  mailEnabled?: boolean;
  mailNickname?: string;
  membershipRule?: string;
  membershipRuleProcessingState?: string;
  onPremisesDomainName?: string;
  onPremisesLastSyncDateTime?: Date;
  onPremisesNetBiosName?: string;
  onPremisesProvisioningErrors?: OnPremisesProvisioningError[];
  onPremisesSamAccountName?: string;
  onPremisesSecurityIdentifier?: string;
  onPremisesSyncEnabled?: boolean;
  preferredDataLocation?: string;
  preferredLanguage?: string;
  proxyAddresses: string[];
  renewedDateTime?: Date;
  securityEnabled?: boolean;
  securityIdentifier?: string;
  theme?: string;
  visibility?: string;
  allowExternalSenders?: boolean;
  autoSubscribeNewMembers?: boolean;
  hideFromAddressLists?: boolean;
  hideFromOutlookClients?: boolean;
  isSubscribedByMail?: boolean;
  unseenCount?: number;
  isArchived?: boolean;
  appRoleAssignments?: AppRoleAssignment[];
  createdOnBehalfOf?: DirectoryObject;
  memberOf?: DirectoryObject[];
  members?: DirectoryObject[];
  membersWithLicenseErrors?: DirectoryObject[];
  owners?: DirectoryObject[];
  permissionGrants?: ResourceSpecificPermissionGrant[];
  settings?: GroupSetting[];
  transitiveMemberOf?: DirectoryObject[];
  transitiveMembers?: DirectoryObject[];
  acceptedSenders?: DirectoryObject[];
  calendar?: Calendar;
  calendarView?: Event[];
  conversations?: Conversation[];
  events?: Event[];
  photo?: ProfilePhoto;
  photos?: ProfilePhoto[];
  rejectedSenders?: DirectoryObject[];
  threads?: ConversationThread[];
  drive?: Drive;
  drives?: Drive[];
  sites?: Site[];
  extensions?: Extension[];
  groupLifecyclePolicies?: GroupLifecyclePolicy[];
  planner?: PlannerGroup;
  onenote?: Onenote;
  team?: Team;
  //#endregion
}