import { EntityConfig } from 'angular-odata';

//#region ODataApi Imports
import { IosGeneralDeviceConfiguration } from './iosgeneraldeviceconfiguration.entity';
//#endregion

export const IosGeneralDeviceConfigurationConfig = {
  name: "iosGeneralDeviceConfiguration",
  base: "microsoft.graph.deviceConfiguration",
  annotations: [],
  fields: {
    accountBlockModification: {type: 'Edm.Boolean', nullable: false},
    activationLockAllowWhenSupervised: {type: 'Edm.Boolean', nullable: false},
    airDropBlocked: {type: 'Edm.Boolean', nullable: false},
    airDropForceUnmanagedDropTarget: {type: 'Edm.Boolean', nullable: false},
    airPlayForcePairingPasswordForOutgoingRequests: {type: 'Edm.Boolean', nullable: false},
    appleWatchBlockPairing: {type: 'Edm.Boolean', nullable: false},
    appleWatchForceWristDetection: {type: 'Edm.Boolean', nullable: false},
    appleNewsBlocked: {type: 'Edm.Boolean', nullable: false},
    appsSingleAppModeList: {type: 'graph.appListItem', collection: true},
    appsVisibilityList: {type: 'graph.appListItem', collection: true},
    appsVisibilityListType: {type: 'graph.appListType', nullable: false},
    appStoreBlockAutomaticDownloads: {type: 'Edm.Boolean', nullable: false},
    appStoreBlocked: {type: 'Edm.Boolean', nullable: false},
    appStoreBlockInAppPurchases: {type: 'Edm.Boolean', nullable: false},
    appStoreBlockUIAppInstallation: {type: 'Edm.Boolean', nullable: false},
    appStoreRequirePassword: {type: 'Edm.Boolean', nullable: false},
    bluetoothBlockModification: {type: 'Edm.Boolean', nullable: false},
    cameraBlocked: {type: 'Edm.Boolean', nullable: false},
    cellularBlockDataRoaming: {type: 'Edm.Boolean', nullable: false},
    cellularBlockGlobalBackgroundFetchWhileRoaming: {type: 'Edm.Boolean', nullable: false},
    cellularBlockPerAppDataModification: {type: 'Edm.Boolean', nullable: false},
    cellularBlockPersonalHotspot: {type: 'Edm.Boolean', nullable: false},
    cellularBlockVoiceRoaming: {type: 'Edm.Boolean', nullable: false},
    certificatesBlockUntrustedTlsCertificates: {type: 'Edm.Boolean', nullable: false},
    classroomAppBlockRemoteScreenObservation: {type: 'Edm.Boolean', nullable: false},
    classroomAppForceUnpromptedScreenObservation: {type: 'Edm.Boolean', nullable: false},
    compliantAppsList: {type: 'graph.appListItem', collection: true},
    compliantAppListType: {type: 'graph.appListType', nullable: false},
    configurationProfileBlockChanges: {type: 'Edm.Boolean', nullable: false},
    definitionLookupBlocked: {type: 'Edm.Boolean', nullable: false},
    deviceBlockEnableRestrictions: {type: 'Edm.Boolean', nullable: false},
    deviceBlockEraseContentAndSettings: {type: 'Edm.Boolean', nullable: false},
    deviceBlockNameModification: {type: 'Edm.Boolean', nullable: false},
    diagnosticDataBlockSubmission: {type: 'Edm.Boolean', nullable: false},
    diagnosticDataBlockSubmissionModification: {type: 'Edm.Boolean', nullable: false},
    documentsBlockManagedDocumentsInUnmanagedApps: {type: 'Edm.Boolean', nullable: false},
    documentsBlockUnmanagedDocumentsInManagedApps: {type: 'Edm.Boolean', nullable: false},
    emailInDomainSuffixes: {type: 'Edm.String', collection: true},
    enterpriseAppBlockTrust: {type: 'Edm.Boolean', nullable: false},
    enterpriseAppBlockTrustModification: {type: 'Edm.Boolean', nullable: false},
    faceTimeBlocked: {type: 'Edm.Boolean', nullable: false},
    findMyFriendsBlocked: {type: 'Edm.Boolean', nullable: false},
    gamingBlockGameCenterFriends: {type: 'Edm.Boolean', nullable: false},
    gamingBlockMultiplayer: {type: 'Edm.Boolean', nullable: false},
    gameCenterBlocked: {type: 'Edm.Boolean', nullable: false},
    hostPairingBlocked: {type: 'Edm.Boolean', nullable: false},
    iBooksStoreBlocked: {type: 'Edm.Boolean', nullable: false},
    iBooksStoreBlockErotica: {type: 'Edm.Boolean', nullable: false},
    iCloudBlockActivityContinuation: {type: 'Edm.Boolean', nullable: false},
    iCloudBlockBackup: {type: 'Edm.Boolean', nullable: false},
    iCloudBlockDocumentSync: {type: 'Edm.Boolean', nullable: false},
    iCloudBlockManagedAppsSync: {type: 'Edm.Boolean', nullable: false},
    iCloudBlockPhotoLibrary: {type: 'Edm.Boolean', nullable: false},
    iCloudBlockPhotoStreamSync: {type: 'Edm.Boolean', nullable: false},
    iCloudBlockSharedPhotoStream: {type: 'Edm.Boolean', nullable: false},
    iCloudRequireEncryptedBackup: {type: 'Edm.Boolean', nullable: false},
    iTunesBlockExplicitContent: {type: 'Edm.Boolean', nullable: false},
    iTunesBlockMusicService: {type: 'Edm.Boolean', nullable: false},
    iTunesBlockRadio: {type: 'Edm.Boolean', nullable: false},
    keyboardBlockAutoCorrect: {type: 'Edm.Boolean', nullable: false},
    keyboardBlockDictation: {type: 'Edm.Boolean', nullable: false},
    keyboardBlockPredictive: {type: 'Edm.Boolean', nullable: false},
    keyboardBlockShortcuts: {type: 'Edm.Boolean', nullable: false},
    keyboardBlockSpellCheck: {type: 'Edm.Boolean', nullable: false},
    kioskModeAllowAssistiveSpeak: {type: 'Edm.Boolean', nullable: false},
    kioskModeAllowAssistiveTouchSettings: {type: 'Edm.Boolean', nullable: false},
    kioskModeAllowAutoLock: {type: 'Edm.Boolean', nullable: false},
    kioskModeAllowColorInversionSettings: {type: 'Edm.Boolean', nullable: false},
    kioskModeAllowRingerSwitch: {type: 'Edm.Boolean', nullable: false},
    kioskModeAllowScreenRotation: {type: 'Edm.Boolean', nullable: false},
    kioskModeAllowSleepButton: {type: 'Edm.Boolean', nullable: false},
    kioskModeAllowTouchscreen: {type: 'Edm.Boolean', nullable: false},
    kioskModeAllowVoiceOverSettings: {type: 'Edm.Boolean', nullable: false},
    kioskModeAllowVolumeButtons: {type: 'Edm.Boolean', nullable: false},
    kioskModeAllowZoomSettings: {type: 'Edm.Boolean', nullable: false},
    kioskModeAppStoreUrl: {type: 'Edm.String'},
    kioskModeBuiltInAppId: {type: 'Edm.String'},
    kioskModeRequireAssistiveTouch: {type: 'Edm.Boolean', nullable: false},
    kioskModeRequireColorInversion: {type: 'Edm.Boolean', nullable: false},
    kioskModeRequireMonoAudio: {type: 'Edm.Boolean', nullable: false},
    kioskModeRequireVoiceOver: {type: 'Edm.Boolean', nullable: false},
    kioskModeRequireZoom: {type: 'Edm.Boolean', nullable: false},
    kioskModeManagedAppId: {type: 'Edm.String'},
    lockScreenBlockControlCenter: {type: 'Edm.Boolean', nullable: false},
    lockScreenBlockNotificationView: {type: 'Edm.Boolean', nullable: false},
    lockScreenBlockPassbook: {type: 'Edm.Boolean', nullable: false},
    lockScreenBlockTodayView: {type: 'Edm.Boolean', nullable: false},
    mediaContentRatingAustralia: {type: 'graph.mediaContentRatingAustralia'},
    mediaContentRatingCanada: {type: 'graph.mediaContentRatingCanada'},
    mediaContentRatingFrance: {type: 'graph.mediaContentRatingFrance'},
    mediaContentRatingGermany: {type: 'graph.mediaContentRatingGermany'},
    mediaContentRatingIreland: {type: 'graph.mediaContentRatingIreland'},
    mediaContentRatingJapan: {type: 'graph.mediaContentRatingJapan'},
    mediaContentRatingNewZealand: {type: 'graph.mediaContentRatingNewZealand'},
    mediaContentRatingUnitedKingdom: {type: 'graph.mediaContentRatingUnitedKingdom'},
    mediaContentRatingUnitedStates: {type: 'graph.mediaContentRatingUnitedStates'},
    networkUsageRules: {type: 'graph.iosNetworkUsageRule', collection: true},
    mediaContentRatingApps: {type: 'graph.ratingAppsType', nullable: false},
    messagesBlocked: {type: 'Edm.Boolean', nullable: false},
    notificationsBlockSettingsModification: {type: 'Edm.Boolean', nullable: false},
    passcodeBlockFingerprintUnlock: {type: 'Edm.Boolean', nullable: false},
    passcodeBlockFingerprintModification: {type: 'Edm.Boolean', nullable: false},
    passcodeBlockModification: {type: 'Edm.Boolean', nullable: false},
    passcodeBlockSimple: {type: 'Edm.Boolean', nullable: false},
    passcodeExpirationDays: {type: 'Edm.Int32'},
    passcodeMinimumLength: {type: 'Edm.Int32'},
    passcodeMinutesOfInactivityBeforeLock: {type: 'Edm.Int32'},
    passcodeMinutesOfInactivityBeforeScreenTimeout: {type: 'Edm.Int32'},
    passcodeMinimumCharacterSetCount: {type: 'Edm.Int32'},
    passcodePreviousPasscodeBlockCount: {type: 'Edm.Int32'},
    passcodeSignInFailureCountBeforeWipe: {type: 'Edm.Int32'},
    passcodeRequiredType: {type: 'graph.requiredPasswordType', nullable: false},
    passcodeRequired: {type: 'Edm.Boolean', nullable: false},
    podcastsBlocked: {type: 'Edm.Boolean', nullable: false},
    safariBlockAutofill: {type: 'Edm.Boolean', nullable: false},
    safariBlockJavaScript: {type: 'Edm.Boolean', nullable: false},
    safariBlockPopups: {type: 'Edm.Boolean', nullable: false},
    safariBlocked: {type: 'Edm.Boolean', nullable: false},
    safariCookieSettings: {type: 'graph.webBrowserCookieSettings', nullable: false},
    safariManagedDomains: {type: 'Edm.String', collection: true},
    safariPasswordAutoFillDomains: {type: 'Edm.String', collection: true},
    safariRequireFraudWarning: {type: 'Edm.Boolean', nullable: false},
    screenCaptureBlocked: {type: 'Edm.Boolean', nullable: false},
    siriBlocked: {type: 'Edm.Boolean', nullable: false},
    siriBlockedWhenLocked: {type: 'Edm.Boolean', nullable: false},
    siriBlockUserGeneratedContent: {type: 'Edm.Boolean', nullable: false},
    siriRequireProfanityFilter: {type: 'Edm.Boolean', nullable: false},
    spotlightBlockInternetResults: {type: 'Edm.Boolean', nullable: false},
    voiceDialingBlocked: {type: 'Edm.Boolean', nullable: false},
    wallpaperBlockModification: {type: 'Edm.Boolean', nullable: false},
    wiFiConnectOnlyToConfiguredNetworks: {type: 'Edm.Boolean', nullable: false}
  }
} as EntityConfig<IosGeneralDeviceConfiguration>;