import { Duration } from 'angular-odata';

//#region ODataApi Imports
import { DirectoryObject } from './directoryobject.entity';
import { AssignedLicense } from './assignedlicense.entity';
import { AssignedPlan } from './assignedplan.entity';
import { ObjectIdentity } from './objectidentity.entity';
import { LicenseAssignmentState } from './licenseassignmentstate.entity';
import { OnPremisesExtensionAttributes } from './onpremisesextensionattributes.entity';
import { OnPremisesProvisioningError } from './onpremisesprovisioningerror.entity';
import { PasswordProfile } from './passwordprofile.entity';
import { ProvisionedPlan } from './provisionedplan.entity';
import { MailboxSettings } from './mailboxsettings.entity';
import { AppRoleAssignment } from './approleassignment.entity';
import { OAuth2PermissionGrant } from './oauth2permissiongrant.entity';
import { LicenseDetails } from './licensedetails.entity';
import { OutlookUser } from './outlookuser.entity';
import { Message } from './message.entity';
import { MailFolder } from './mailfolder.entity';
import { Calendar } from './calendar.entity';
import { CalendarGroup } from './calendargroup.entity';
import { Event } from './event.entity';
import { Person } from './person.entity';
import { Contact } from './contact.entity';
import { ContactFolder } from './contactfolder.entity';
import { InferenceClassification } from './inferenceclassification.entity';
import { ProfilePhoto } from './profilephoto.entity';
import { Drive } from './drive.entity';
import { Site } from './site.entity';
import { Extension } from './extension.entity';
import { ManagedDevice } from './manageddevice.entity';
import { ManagedAppRegistration } from './managedappregistration.entity';
import { DeviceManagementTroubleshootingEvent } from './devicemanagementtroubleshootingevent.entity';
import { PlannerUser } from './planneruser.entity';
import { OfficeGraphInsights } from './officegraphinsights.entity';
import { UserSettings } from './usersettings.entity';
import { Onenote } from './onenote.entity';
import { UserActivity } from './useractivity.entity';
import { OnlineMeeting } from './onlinemeeting.entity';
import { Team } from './team.entity';
//#endregion

export interface User extends DirectoryObject {
  //#region ODataApi Properties
  accountEnabled?: boolean;
  ageGroup?: string;
  assignedLicenses: AssignedLicense[];
  assignedPlans: AssignedPlan[];
  businessPhones: string[];
  city?: string;
  companyName?: string;
  consentProvidedForMinor?: string;
  country?: string;
  creationType?: string;
  department?: string;
  displayName?: string;
  employeeId?: string;
  externalUserState?: string;
  externalUserStateChangeDateTime?: Date;
  faxNumber?: string;
  givenName?: string;
  identities?: ObjectIdentity[];
  imAddresses?: string[];
  isResourceAccount?: boolean;
  jobTitle?: string;
  lastPasswordChangeDateTime?: Date;
  legalAgeGroupClassification?: string;
  licenseAssignmentStates?: LicenseAssignmentState[];
  mail?: string;
  mailNickname?: string;
  mobilePhone?: string;
  onPremisesDistinguishedName?: string;
  onPremisesExtensionAttributes?: OnPremisesExtensionAttributes;
  onPremisesImmutableId?: string;
  onPremisesLastSyncDateTime?: Date;
  onPremisesProvisioningErrors?: OnPremisesProvisioningError[];
  onPremisesSecurityIdentifier?: string;
  onPremisesSyncEnabled?: boolean;
  onPremisesDomainName?: string;
  onPremisesSamAccountName?: string;
  onPremisesUserPrincipalName?: string;
  otherMails: string[];
  passwordPolicies?: string;
  passwordProfile?: PasswordProfile;
  officeLocation?: string;
  postalCode?: string;
  preferredLanguage?: string;
  provisionedPlans: ProvisionedPlan[];
  proxyAddresses: string[];
  showInAddressList?: boolean;
  signInSessionsValidFromDateTime?: Date;
  state?: string;
  streetAddress?: string;
  surname?: string;
  usageLocation?: string;
  userPrincipalName?: string;
  userType?: string;
  mailboxSettings?: MailboxSettings;
  deviceEnrollmentLimit: number;
  aboutMe?: string;
  birthday: Date;
  hireDate: Date;
  interests?: string[];
  mySite?: string;
  pastProjects?: string[];
  preferredName?: string;
  responsibilities?: string[];
  schools?: string[];
  skills?: string[];
  appRoleAssignments?: AppRoleAssignment[];
  ownedDevices?: DirectoryObject[];
  registeredDevices?: DirectoryObject[];
  manager?: DirectoryObject;
  directReports?: DirectoryObject[];
  memberOf?: DirectoryObject[];
  createdObjects?: DirectoryObject[];
  oauth2PermissionGrants?: OAuth2PermissionGrant[];
  ownedObjects?: DirectoryObject[];
  licenseDetails?: LicenseDetails[];
  transitiveMemberOf?: DirectoryObject[];
  outlook?: OutlookUser;
  messages?: Message[];
  mailFolders?: MailFolder[];
  calendar?: Calendar;
  calendars?: Calendar[];
  calendarGroups?: CalendarGroup[];
  calendarView?: Event[];
  events?: Event[];
  people?: Person[];
  contacts?: Contact[];
  contactFolders?: ContactFolder[];
  inferenceClassification?: InferenceClassification;
  photo?: ProfilePhoto;
  photos?: ProfilePhoto[];
  drive?: Drive;
  drives?: Drive[];
  followedSites?: Site[];
  extensions?: Extension[];
  managedDevices?: ManagedDevice[];
  managedAppRegistrations?: ManagedAppRegistration[];
  deviceManagementTroubleshootingEvents?: DeviceManagementTroubleshootingEvent[];
  planner?: PlannerUser;
  insights?: OfficeGraphInsights;
  settings?: UserSettings;
  onenote?: Onenote;
  activities?: UserActivity[];
  onlineMeetings?: OnlineMeeting[];
  joinedTeams?: Team[];
  //#endregion
}