import { Duration } from 'angular-odata';

//#region ODataApi Imports
import { DeviceConfiguration } from './deviceconfiguration.entity';
import { RequiredPasswordType } from './requiredpasswordtype.enum';
import { StateManagementSetting } from './statemanagementsetting.enum';
import { DefenderCloudBlockLevelType } from './defendercloudblockleveltype.enum';
import { DefenderScanType } from './defenderscantype.enum';
import { WeeklySchedule } from './weeklyschedule.enum';
import { DiagnosticDataSubmissionMode } from './diagnosticdatasubmissionmode.enum';
import { EdgeCookiePolicy } from './edgecookiepolicy.enum';
import { VisibilitySetting } from './visibilitysetting.enum';
import { DefenderMonitorFileActivity } from './defendermonitorfileactivity.enum';
import { DefenderPromptForSampleSubmission } from './defenderpromptforsamplesubmission.enum';
import { WindowsStartMenuAppListVisibilityType } from './windowsstartmenuapplistvisibilitytype.enum';
import { WindowsStartMenuModeType } from './windowsstartmenumodetype.enum';
import { WindowsSpotlightEnablementSettings } from './windowsspotlightenablementsettings.enum';
import { SafeSearchFilterType } from './safesearchfiltertype.enum';
import { DefenderDetectedMalwareActions } from './defenderdetectedmalwareactions.entity';
import { Windows10NetworkProxyServer } from './windows10networkproxyserver.entity';
import { EdgeSearchEngineBase } from './edgesearchenginebase.entity';
//#endregion

export interface Windows10GeneralConfiguration extends DeviceConfiguration {
  //#region ODataApi Properties
  enterpriseCloudPrintDiscoveryEndPoint?: string;
  enterpriseCloudPrintOAuthAuthority?: string;
  enterpriseCloudPrintOAuthClientIdentifier?: string;
  enterpriseCloudPrintResourceIdentifier?: string;
  enterpriseCloudPrintDiscoveryMaxLimit?: number;
  enterpriseCloudPrintMopriaDiscoveryResourceIdentifier?: string;
  searchBlockDiacritics: boolean;
  searchDisableAutoLanguageDetection: boolean;
  searchDisableIndexingEncryptedItems: boolean;
  searchEnableRemoteQueries: boolean;
  searchDisableIndexerBackoff: boolean;
  searchDisableIndexingRemovableDrive: boolean;
  searchEnableAutomaticIndexSizeManangement: boolean;
  diagnosticsDataSubmissionMode: DiagnosticDataSubmissionMode;
  oneDriveDisableFileSync: boolean;
  smartScreenEnableAppInstallControl: boolean;
  personalizationDesktopImageUrl?: string;
  personalizationLockScreenImageUrl?: string;
  bluetoothAllowedServices?: string[];
  bluetoothBlockAdvertising: boolean;
  bluetoothBlockDiscoverableMode: boolean;
  bluetoothBlockPrePairing: boolean;
  edgeBlockAutofill: boolean;
  edgeBlocked: boolean;
  edgeCookiePolicy: EdgeCookiePolicy;
  edgeBlockDeveloperTools: boolean;
  edgeBlockSendingDoNotTrackHeader: boolean;
  edgeBlockExtensions: boolean;
  edgeBlockInPrivateBrowsing: boolean;
  edgeBlockJavaScript: boolean;
  edgeBlockPasswordManager: boolean;
  edgeBlockAddressBarDropdown: boolean;
  edgeBlockCompatibilityList: boolean;
  edgeClearBrowsingDataOnExit: boolean;
  edgeAllowStartPagesModification: boolean;
  edgeDisableFirstRunPage: boolean;
  edgeBlockLiveTileDataCollection: boolean;
  edgeSyncFavoritesWithInternetExplorer: boolean;
  cellularBlockDataWhenRoaming: boolean;
  cellularBlockVpn: boolean;
  cellularBlockVpnWhenRoaming: boolean;
  defenderBlockEndUserAccess: boolean;
  defenderDaysBeforeDeletingQuarantinedMalware?: number;
  defenderDetectedMalwareActions?: DefenderDetectedMalwareActions;
  defenderSystemScanSchedule: WeeklySchedule;
  defenderFilesAndFoldersToExclude?: string[];
  defenderFileExtensionsToExclude?: string[];
  defenderScanMaxCpu?: number;
  defenderMonitorFileActivity: DefenderMonitorFileActivity;
  defenderProcessesToExclude?: string[];
  defenderPromptForSampleSubmission: DefenderPromptForSampleSubmission;
  defenderRequireBehaviorMonitoring: boolean;
  defenderRequireCloudProtection: boolean;
  defenderRequireNetworkInspectionSystem: boolean;
  defenderRequireRealTimeMonitoring: boolean;
  defenderScanArchiveFiles: boolean;
  defenderScanDownloads: boolean;
  defenderScanNetworkFiles: boolean;
  defenderScanIncomingMail: boolean;
  defenderScanMappedNetworkDrivesDuringFullScan: boolean;
  defenderScanRemovableDrivesDuringFullScan: boolean;
  defenderScanScriptsLoadedInInternetExplorer: boolean;
  defenderSignatureUpdateIntervalInHours?: number;
  defenderScanType: DefenderScanType;
  defenderScheduledScanTime?: Date;
  defenderScheduledQuickScanTime?: Date;
  defenderCloudBlockLevel: DefenderCloudBlockLevelType;
  lockScreenAllowTimeoutConfiguration: boolean;
  lockScreenBlockActionCenterNotifications: boolean;
  lockScreenBlockCortana: boolean;
  lockScreenBlockToastNotifications: boolean;
  lockScreenTimeoutInSeconds?: number;
  passwordBlockSimple: boolean;
  passwordExpirationDays?: number;
  passwordMinimumLength?: number;
  passwordMinutesOfInactivityBeforeScreenTimeout?: number;
  passwordMinimumCharacterSetCount?: number;
  passwordPreviousPasswordBlockCount?: number;
  passwordRequired: boolean;
  passwordRequireWhenResumeFromIdleState: boolean;
  passwordRequiredType: RequiredPasswordType;
  passwordSignInFailureCountBeforeFactoryReset?: number;
  privacyAdvertisingId: StateManagementSetting;
  privacyAutoAcceptPairingAndConsentPrompts: boolean;
  privacyBlockInputPersonalization: boolean;
  startBlockUnpinningAppsFromTaskbar: boolean;
  startMenuAppListVisibility: WindowsStartMenuAppListVisibilityType;
  startMenuHideChangeAccountSettings: boolean;
  startMenuHideFrequentlyUsedApps: boolean;
  startMenuHideHibernate: boolean;
  startMenuHideLock: boolean;
  startMenuHidePowerButton: boolean;
  startMenuHideRecentJumpLists: boolean;
  startMenuHideRecentlyAddedApps: boolean;
  startMenuHideRestartOptions: boolean;
  startMenuHideShutDown: boolean;
  startMenuHideSignOut: boolean;
  startMenuHideSleep: boolean;
  startMenuHideSwitchAccount: boolean;
  startMenuHideUserTile: boolean;
  startMenuLayoutEdgeAssetsXml?: ArrayBuffer;
  startMenuLayoutXml?: ArrayBuffer;
  startMenuMode: WindowsStartMenuModeType;
  startMenuPinnedFolderDocuments: VisibilitySetting;
  startMenuPinnedFolderDownloads: VisibilitySetting;
  startMenuPinnedFolderFileExplorer: VisibilitySetting;
  startMenuPinnedFolderHomeGroup: VisibilitySetting;
  startMenuPinnedFolderMusic: VisibilitySetting;
  startMenuPinnedFolderNetwork: VisibilitySetting;
  startMenuPinnedFolderPersonalFolder: VisibilitySetting;
  startMenuPinnedFolderPictures: VisibilitySetting;
  startMenuPinnedFolderSettings: VisibilitySetting;
  startMenuPinnedFolderVideos: VisibilitySetting;
  settingsBlockSettingsApp: boolean;
  settingsBlockSystemPage: boolean;
  settingsBlockDevicesPage: boolean;
  settingsBlockNetworkInternetPage: boolean;
  settingsBlockPersonalizationPage: boolean;
  settingsBlockAccountsPage: boolean;
  settingsBlockTimeLanguagePage: boolean;
  settingsBlockEaseOfAccessPage: boolean;
  settingsBlockPrivacyPage: boolean;
  settingsBlockUpdateSecurityPage: boolean;
  settingsBlockAppsPage: boolean;
  settingsBlockGamingPage: boolean;
  windowsSpotlightBlockConsumerSpecificFeatures: boolean;
  windowsSpotlightBlocked: boolean;
  windowsSpotlightBlockOnActionCenter: boolean;
  windowsSpotlightBlockTailoredExperiences: boolean;
  windowsSpotlightBlockThirdPartyNotifications: boolean;
  windowsSpotlightBlockWelcomeExperience: boolean;
  windowsSpotlightBlockWindowsTips: boolean;
  windowsSpotlightConfigureOnLockScreen: WindowsSpotlightEnablementSettings;
  networkProxyApplySettingsDeviceWide: boolean;
  networkProxyDisableAutoDetect: boolean;
  networkProxyAutomaticConfigurationUrl?: string;
  networkProxyServer?: Windows10NetworkProxyServer;
  accountsBlockAddingNonMicrosoftAccountEmail: boolean;
  antiTheftModeBlocked: boolean;
  bluetoothBlocked: boolean;
  cameraBlocked: boolean;
  connectedDevicesServiceBlocked: boolean;
  certificatesBlockManualRootCertificateInstallation: boolean;
  copyPasteBlocked: boolean;
  cortanaBlocked: boolean;
  deviceManagementBlockFactoryResetOnMobile: boolean;
  deviceManagementBlockManualUnenroll: boolean;
  safeSearchFilter: SafeSearchFilterType;
  edgeBlockPopups: boolean;
  edgeBlockSearchSuggestions: boolean;
  edgeBlockSendingIntranetTrafficToInternetExplorer: boolean;
  edgeSendIntranetTrafficToInternetExplorer: boolean;
  edgeRequireSmartScreen: boolean;
  edgeEnterpriseModeSiteListLocation?: string;
  edgeFirstRunUrl?: string;
  edgeSearchEngine?: EdgeSearchEngineBase;
  edgeHomepageUrls?: string[];
  edgeBlockAccessToAboutFlags: boolean;
  smartScreenBlockPromptOverride: boolean;
  smartScreenBlockPromptOverrideForFiles: boolean;
  webRtcBlockLocalhostIpAddress: boolean;
  internetSharingBlocked: boolean;
  settingsBlockAddProvisioningPackage: boolean;
  settingsBlockRemoveProvisioningPackage: boolean;
  settingsBlockChangeSystemTime: boolean;
  settingsBlockEditDeviceName: boolean;
  settingsBlockChangeRegion: boolean;
  settingsBlockChangeLanguage: boolean;
  settingsBlockChangePowerSleep: boolean;
  locationServicesBlocked: boolean;
  microsoftAccountBlocked: boolean;
  microsoftAccountBlockSettingsSync: boolean;
  nfcBlocked: boolean;
  resetProtectionModeBlocked: boolean;
  screenCaptureBlocked: boolean;
  storageBlockRemovableStorage: boolean;
  storageRequireMobileDeviceEncryption: boolean;
  usbBlocked: boolean;
  voiceRecordingBlocked: boolean;
  wiFiBlockAutomaticConnectHotspots: boolean;
  wiFiBlocked: boolean;
  wiFiBlockManualConfiguration: boolean;
  wiFiScanInterval?: number;
  wirelessDisplayBlockProjectionToThisDevice: boolean;
  wirelessDisplayBlockUserInputFromReceiver: boolean;
  wirelessDisplayRequirePinForPairing: boolean;
  windowsStoreBlocked: boolean;
  appsAllowTrustedAppsSideloading: StateManagementSetting;
  windowsStoreBlockAutoUpdate: boolean;
  developerUnlockSetting: StateManagementSetting;
  sharedUserAppDataAllowed: boolean;
  appsBlockWindowsStoreOriginatedApps: boolean;
  windowsStoreEnablePrivateStoreOnly: boolean;
  storageRestrictAppDataToSystemVolume: boolean;
  storageRestrictAppInstallToSystemVolume: boolean;
  gameDvrBlocked: boolean;
  experienceBlockDeviceDiscovery: boolean;
  experienceBlockErrorDialogWhenNoSIM: boolean;
  experienceBlockTaskSwitcher: boolean;
  logonBlockFastUserSwitching: boolean;
  tenantLockdownRequireNetworkDuringOutOfBoxExperience: boolean;
  //#endregion
}