import { EntityConfig } from 'angular-odata';

//#region ODataApi Imports
import { Windows10GeneralConfiguration } from './windows10generalconfiguration.entity';
import { Windows10GeneralConfigurationModel } from './windows10generalconfiguration.model';
import { Windows10GeneralConfigurationCollection } from './windows10generalconfiguration.collection';
//#endregion

export const Windows10GeneralConfigurationConfig = {
  name: "windows10GeneralConfiguration",
  base: "microsoft.graph.deviceConfiguration",
  model: Windows10GeneralConfigurationModel,
  collection: Windows10GeneralConfigurationCollection,
  annotations: [],
  fields: {
    accountsBlockAddingNonMicrosoftAccountEmail: {type: 'Edm.Boolean', nullable: false},
    antiTheftModeBlocked: {type: 'Edm.Boolean', nullable: false},
    appsAllowTrustedAppsSideloading: {type: 'graph.stateManagementSetting', nullable: false},
    appsBlockWindowsStoreOriginatedApps: {type: 'Edm.Boolean', nullable: false},
    bluetoothAllowedServices: {type: 'Edm.String', collection: true},
    bluetoothBlockAdvertising: {type: 'Edm.Boolean', nullable: false},
    bluetoothBlockDiscoverableMode: {type: 'Edm.Boolean', nullable: false},
    bluetoothBlocked: {type: 'Edm.Boolean', nullable: false},
    bluetoothBlockPrePairing: {type: 'Edm.Boolean', nullable: false},
    cameraBlocked: {type: 'Edm.Boolean', nullable: false},
    cellularBlockDataWhenRoaming: {type: 'Edm.Boolean', nullable: false},
    cellularBlockVpn: {type: 'Edm.Boolean', nullable: false},
    cellularBlockVpnWhenRoaming: {type: 'Edm.Boolean', nullable: false},
    certificatesBlockManualRootCertificateInstallation: {type: 'Edm.Boolean', nullable: false},
    connectedDevicesServiceBlocked: {type: 'Edm.Boolean', nullable: false},
    copyPasteBlocked: {type: 'Edm.Boolean', nullable: false},
    cortanaBlocked: {type: 'Edm.Boolean', nullable: false},
    defenderBlockEndUserAccess: {type: 'Edm.Boolean', nullable: false},
    defenderCloudBlockLevel: {type: 'graph.defenderCloudBlockLevelType', nullable: false},
    defenderDaysBeforeDeletingQuarantinedMalware: {type: 'Edm.Int32'},
    defenderDetectedMalwareActions: {type: 'graph.defenderDetectedMalwareActions'},
    defenderFileExtensionsToExclude: {type: 'Edm.String', collection: true},
    defenderFilesAndFoldersToExclude: {type: 'Edm.String', collection: true},
    defenderMonitorFileActivity: {type: 'graph.defenderMonitorFileActivity', nullable: false},
    defenderProcessesToExclude: {type: 'Edm.String', collection: true},
    defenderPromptForSampleSubmission: {type: 'graph.defenderPromptForSampleSubmission', nullable: false},
    defenderRequireBehaviorMonitoring: {type: 'Edm.Boolean', nullable: false},
    defenderRequireCloudProtection: {type: 'Edm.Boolean', nullable: false},
    defenderRequireNetworkInspectionSystem: {type: 'Edm.Boolean', nullable: false},
    defenderRequireRealTimeMonitoring: {type: 'Edm.Boolean', nullable: false},
    defenderScanArchiveFiles: {type: 'Edm.Boolean', nullable: false},
    defenderScanDownloads: {type: 'Edm.Boolean', nullable: false},
    defenderScanIncomingMail: {type: 'Edm.Boolean', nullable: false},
    defenderScanMappedNetworkDrivesDuringFullScan: {type: 'Edm.Boolean', nullable: false},
    defenderScanMaxCpu: {type: 'Edm.Int32'},
    defenderScanNetworkFiles: {type: 'Edm.Boolean', nullable: false},
    defenderScanRemovableDrivesDuringFullScan: {type: 'Edm.Boolean', nullable: false},
    defenderScanScriptsLoadedInInternetExplorer: {type: 'Edm.Boolean', nullable: false},
    defenderScanType: {type: 'graph.defenderScanType', nullable: false},
    defenderScheduledQuickScanTime: {type: 'Edm.TimeOfDay'},
    defenderScheduledScanTime: {type: 'Edm.TimeOfDay'},
    defenderSignatureUpdateIntervalInHours: {type: 'Edm.Int32'},
    defenderSystemScanSchedule: {type: 'graph.weeklySchedule', nullable: false},
    developerUnlockSetting: {type: 'graph.stateManagementSetting', nullable: false},
    deviceManagementBlockFactoryResetOnMobile: {type: 'Edm.Boolean', nullable: false},
    deviceManagementBlockManualUnenroll: {type: 'Edm.Boolean', nullable: false},
    diagnosticsDataSubmissionMode: {type: 'graph.diagnosticDataSubmissionMode', nullable: false},
    edgeAllowStartPagesModification: {type: 'Edm.Boolean', nullable: false},
    edgeBlockAccessToAboutFlags: {type: 'Edm.Boolean', nullable: false},
    edgeBlockAddressBarDropdown: {type: 'Edm.Boolean', nullable: false},
    edgeBlockAutofill: {type: 'Edm.Boolean', nullable: false},
    edgeBlockCompatibilityList: {type: 'Edm.Boolean', nullable: false},
    edgeBlockDeveloperTools: {type: 'Edm.Boolean', nullable: false},
    edgeBlocked: {type: 'Edm.Boolean', nullable: false},
    edgeBlockExtensions: {type: 'Edm.Boolean', nullable: false},
    edgeBlockInPrivateBrowsing: {type: 'Edm.Boolean', nullable: false},
    edgeBlockJavaScript: {type: 'Edm.Boolean', nullable: false},
    edgeBlockLiveTileDataCollection: {type: 'Edm.Boolean', nullable: false},
    edgeBlockPasswordManager: {type: 'Edm.Boolean', nullable: false},
    edgeBlockPopups: {type: 'Edm.Boolean', nullable: false},
    edgeBlockSearchSuggestions: {type: 'Edm.Boolean', nullable: false},
    edgeBlockSendingDoNotTrackHeader: {type: 'Edm.Boolean', nullable: false},
    edgeBlockSendingIntranetTrafficToInternetExplorer: {type: 'Edm.Boolean', nullable: false},
    edgeClearBrowsingDataOnExit: {type: 'Edm.Boolean', nullable: false},
    edgeCookiePolicy: {type: 'graph.edgeCookiePolicy', nullable: false},
    edgeDisableFirstRunPage: {type: 'Edm.Boolean', nullable: false},
    edgeEnterpriseModeSiteListLocation: {type: 'Edm.String'},
    edgeFirstRunUrl: {type: 'Edm.String'},
    edgeHomepageUrls: {type: 'Edm.String', collection: true},
    edgeRequireSmartScreen: {type: 'Edm.Boolean', nullable: false},
    edgeSearchEngine: {type: 'graph.edgeSearchEngineBase'},
    edgeSendIntranetTrafficToInternetExplorer: {type: 'Edm.Boolean', nullable: false},
    edgeSyncFavoritesWithInternetExplorer: {type: 'Edm.Boolean', nullable: false},
    enterpriseCloudPrintDiscoveryEndPoint: {type: 'Edm.String'},
    enterpriseCloudPrintDiscoveryMaxLimit: {type: 'Edm.Int32'},
    enterpriseCloudPrintMopriaDiscoveryResourceIdentifier: {type: 'Edm.String'},
    enterpriseCloudPrintOAuthAuthority: {type: 'Edm.String'},
    enterpriseCloudPrintOAuthClientIdentifier: {type: 'Edm.String'},
    enterpriseCloudPrintResourceIdentifier: {type: 'Edm.String'},
    experienceBlockDeviceDiscovery: {type: 'Edm.Boolean', nullable: false},
    experienceBlockErrorDialogWhenNoSIM: {type: 'Edm.Boolean', nullable: false},
    experienceBlockTaskSwitcher: {type: 'Edm.Boolean', nullable: false},
    gameDvrBlocked: {type: 'Edm.Boolean', nullable: false},
    internetSharingBlocked: {type: 'Edm.Boolean', nullable: false},
    locationServicesBlocked: {type: 'Edm.Boolean', nullable: false},
    lockScreenAllowTimeoutConfiguration: {type: 'Edm.Boolean', nullable: false},
    lockScreenBlockActionCenterNotifications: {type: 'Edm.Boolean', nullable: false},
    lockScreenBlockCortana: {type: 'Edm.Boolean', nullable: false},
    lockScreenBlockToastNotifications: {type: 'Edm.Boolean', nullable: false},
    lockScreenTimeoutInSeconds: {type: 'Edm.Int32'},
    logonBlockFastUserSwitching: {type: 'Edm.Boolean', nullable: false},
    microsoftAccountBlocked: {type: 'Edm.Boolean', nullable: false},
    microsoftAccountBlockSettingsSync: {type: 'Edm.Boolean', nullable: false},
    networkProxyApplySettingsDeviceWide: {type: 'Edm.Boolean', nullable: false},
    networkProxyAutomaticConfigurationUrl: {type: 'Edm.String'},
    networkProxyDisableAutoDetect: {type: 'Edm.Boolean', nullable: false},
    networkProxyServer: {type: 'graph.windows10NetworkProxyServer'},
    nfcBlocked: {type: 'Edm.Boolean', nullable: false},
    oneDriveDisableFileSync: {type: 'Edm.Boolean', nullable: false},
    passwordBlockSimple: {type: 'Edm.Boolean', nullable: false},
    passwordExpirationDays: {type: 'Edm.Int32'},
    passwordMinimumCharacterSetCount: {type: 'Edm.Int32'},
    passwordMinimumLength: {type: 'Edm.Int32'},
    passwordMinutesOfInactivityBeforeScreenTimeout: {type: 'Edm.Int32'},
    passwordPreviousPasswordBlockCount: {type: 'Edm.Int32'},
    passwordRequired: {type: 'Edm.Boolean', nullable: false},
    passwordRequiredType: {type: 'graph.requiredPasswordType', nullable: false},
    passwordRequireWhenResumeFromIdleState: {type: 'Edm.Boolean', nullable: false},
    passwordSignInFailureCountBeforeFactoryReset: {type: 'Edm.Int32'},
    personalizationDesktopImageUrl: {type: 'Edm.String'},
    personalizationLockScreenImageUrl: {type: 'Edm.String'},
    privacyAdvertisingId: {type: 'graph.stateManagementSetting', nullable: false},
    privacyAutoAcceptPairingAndConsentPrompts: {type: 'Edm.Boolean', nullable: false},
    privacyBlockInputPersonalization: {type: 'Edm.Boolean', nullable: false},
    resetProtectionModeBlocked: {type: 'Edm.Boolean', nullable: false},
    safeSearchFilter: {type: 'graph.safeSearchFilterType', nullable: false},
    screenCaptureBlocked: {type: 'Edm.Boolean', nullable: false},
    searchBlockDiacritics: {type: 'Edm.Boolean', nullable: false},
    searchDisableAutoLanguageDetection: {type: 'Edm.Boolean', nullable: false},
    searchDisableIndexerBackoff: {type: 'Edm.Boolean', nullable: false},
    searchDisableIndexingEncryptedItems: {type: 'Edm.Boolean', nullable: false},
    searchDisableIndexingRemovableDrive: {type: 'Edm.Boolean', nullable: false},
    searchEnableAutomaticIndexSizeManangement: {type: 'Edm.Boolean', nullable: false},
    searchEnableRemoteQueries: {type: 'Edm.Boolean', nullable: false},
    settingsBlockAccountsPage: {type: 'Edm.Boolean', nullable: false},
    settingsBlockAddProvisioningPackage: {type: 'Edm.Boolean', nullable: false},
    settingsBlockAppsPage: {type: 'Edm.Boolean', nullable: false},
    settingsBlockChangeLanguage: {type: 'Edm.Boolean', nullable: false},
    settingsBlockChangePowerSleep: {type: 'Edm.Boolean', nullable: false},
    settingsBlockChangeRegion: {type: 'Edm.Boolean', nullable: false},
    settingsBlockChangeSystemTime: {type: 'Edm.Boolean', nullable: false},
    settingsBlockDevicesPage: {type: 'Edm.Boolean', nullable: false},
    settingsBlockEaseOfAccessPage: {type: 'Edm.Boolean', nullable: false},
    settingsBlockEditDeviceName: {type: 'Edm.Boolean', nullable: false},
    settingsBlockGamingPage: {type: 'Edm.Boolean', nullable: false},
    settingsBlockNetworkInternetPage: {type: 'Edm.Boolean', nullable: false},
    settingsBlockPersonalizationPage: {type: 'Edm.Boolean', nullable: false},
    settingsBlockPrivacyPage: {type: 'Edm.Boolean', nullable: false},
    settingsBlockRemoveProvisioningPackage: {type: 'Edm.Boolean', nullable: false},
    settingsBlockSettingsApp: {type: 'Edm.Boolean', nullable: false},
    settingsBlockSystemPage: {type: 'Edm.Boolean', nullable: false},
    settingsBlockTimeLanguagePage: {type: 'Edm.Boolean', nullable: false},
    settingsBlockUpdateSecurityPage: {type: 'Edm.Boolean', nullable: false},
    sharedUserAppDataAllowed: {type: 'Edm.Boolean', nullable: false},
    smartScreenBlockPromptOverride: {type: 'Edm.Boolean', nullable: false},
    smartScreenBlockPromptOverrideForFiles: {type: 'Edm.Boolean', nullable: false},
    smartScreenEnableAppInstallControl: {type: 'Edm.Boolean', nullable: false},
    startBlockUnpinningAppsFromTaskbar: {type: 'Edm.Boolean', nullable: false},
    startMenuAppListVisibility: {type: 'graph.windowsStartMenuAppListVisibilityType', nullable: false},
    startMenuHideChangeAccountSettings: {type: 'Edm.Boolean', nullable: false},
    startMenuHideFrequentlyUsedApps: {type: 'Edm.Boolean', nullable: false},
    startMenuHideHibernate: {type: 'Edm.Boolean', nullable: false},
    startMenuHideLock: {type: 'Edm.Boolean', nullable: false},
    startMenuHidePowerButton: {type: 'Edm.Boolean', nullable: false},
    startMenuHideRecentJumpLists: {type: 'Edm.Boolean', nullable: false},
    startMenuHideRecentlyAddedApps: {type: 'Edm.Boolean', nullable: false},
    startMenuHideRestartOptions: {type: 'Edm.Boolean', nullable: false},
    startMenuHideShutDown: {type: 'Edm.Boolean', nullable: false},
    startMenuHideSignOut: {type: 'Edm.Boolean', nullable: false},
    startMenuHideSleep: {type: 'Edm.Boolean', nullable: false},
    startMenuHideSwitchAccount: {type: 'Edm.Boolean', nullable: false},
    startMenuHideUserTile: {type: 'Edm.Boolean', nullable: false},
    startMenuLayoutEdgeAssetsXml: {type: 'Edm.Binary'},
    startMenuLayoutXml: {type: 'Edm.Binary'},
    startMenuMode: {type: 'graph.windowsStartMenuModeType', nullable: false},
    startMenuPinnedFolderDocuments: {type: 'graph.visibilitySetting', nullable: false},
    startMenuPinnedFolderDownloads: {type: 'graph.visibilitySetting', nullable: false},
    startMenuPinnedFolderFileExplorer: {type: 'graph.visibilitySetting', nullable: false},
    startMenuPinnedFolderHomeGroup: {type: 'graph.visibilitySetting', nullable: false},
    startMenuPinnedFolderMusic: {type: 'graph.visibilitySetting', nullable: false},
    startMenuPinnedFolderNetwork: {type: 'graph.visibilitySetting', nullable: false},
    startMenuPinnedFolderPersonalFolder: {type: 'graph.visibilitySetting', nullable: false},
    startMenuPinnedFolderPictures: {type: 'graph.visibilitySetting', nullable: false},
    startMenuPinnedFolderSettings: {type: 'graph.visibilitySetting', nullable: false},
    startMenuPinnedFolderVideos: {type: 'graph.visibilitySetting', nullable: false},
    storageBlockRemovableStorage: {type: 'Edm.Boolean', nullable: false},
    storageRequireMobileDeviceEncryption: {type: 'Edm.Boolean', nullable: false},
    storageRestrictAppDataToSystemVolume: {type: 'Edm.Boolean', nullable: false},
    storageRestrictAppInstallToSystemVolume: {type: 'Edm.Boolean', nullable: false},
    tenantLockdownRequireNetworkDuringOutOfBoxExperience: {type: 'Edm.Boolean', nullable: false},
    usbBlocked: {type: 'Edm.Boolean', nullable: false},
    voiceRecordingBlocked: {type: 'Edm.Boolean', nullable: false},
    webRtcBlockLocalhostIpAddress: {type: 'Edm.Boolean', nullable: false},
    wiFiBlockAutomaticConnectHotspots: {type: 'Edm.Boolean', nullable: false},
    wiFiBlocked: {type: 'Edm.Boolean', nullable: false},
    wiFiBlockManualConfiguration: {type: 'Edm.Boolean', nullable: false},
    wiFiScanInterval: {type: 'Edm.Int32'},
    windowsSpotlightBlockConsumerSpecificFeatures: {type: 'Edm.Boolean', nullable: false},
    windowsSpotlightBlocked: {type: 'Edm.Boolean', nullable: false},
    windowsSpotlightBlockOnActionCenter: {type: 'Edm.Boolean', nullable: false},
    windowsSpotlightBlockTailoredExperiences: {type: 'Edm.Boolean', nullable: false},
    windowsSpotlightBlockThirdPartyNotifications: {type: 'Edm.Boolean', nullable: false},
    windowsSpotlightBlockWelcomeExperience: {type: 'Edm.Boolean', nullable: false},
    windowsSpotlightBlockWindowsTips: {type: 'Edm.Boolean', nullable: false},
    windowsSpotlightConfigureOnLockScreen: {type: 'graph.windowsSpotlightEnablementSettings', nullable: false},
    windowsStoreBlockAutoUpdate: {type: 'Edm.Boolean', nullable: false},
    windowsStoreBlocked: {type: 'Edm.Boolean', nullable: false},
    windowsStoreEnablePrivateStoreOnly: {type: 'Edm.Boolean', nullable: false},
    wirelessDisplayBlockProjectionToThisDevice: {type: 'Edm.Boolean', nullable: false},
    wirelessDisplayBlockUserInputFromReceiver: {type: 'Edm.Boolean', nullable: false},
    wirelessDisplayRequirePinForPairing: {type: 'Edm.Boolean', nullable: false}
  }
} as EntityConfig<Windows10GeneralConfiguration>;